# Numpy

Numpy is a linear algebra library for python

In [1]:
import numpy as np

In [2]:
np.arange(10,50)  #  creates a python list kind

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [4]:
np.zeros((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [5]:
np.ones((4,2), dtype = int)    # rows = 4, col = 2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [6]:
random_nums = np.random.randint(1, 100, 7) # generates 7 random numbers between 1 to 100
print(random_nums)

[57 93 71 60 15 45 65]


In [7]:
matrix = np.arange((12), dtype = int).reshape(4,3)
matrix                                  # geneates a mtrix starting from 0 to 11 and arranges them into 4 rows and 3 columns

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
matrix.shape

(4, 3)

In [9]:
matrix.min()

0

In [10]:
matrix.max()

11

In [11]:
matrix.mean()

5.5

In [12]:
np.linspace(0,10,50) # displays numbers from 0 t0 10 with 50 equal parts

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [13]:
np.linspace(2, 12, 6)

array([  2.,   4.,   6.,   8.,  10.,  12.])

In [14]:
A = np.array([[3,2], [4,1]])

In [15]:
A

array([[3, 2],
       [4, 1]])

In [16]:
B = np.array([[7,2], [9,3]])
B

array([[7, 2],
       [9, 3]])

In [17]:
A + B

array([[10,  4],
       [13,  4]])

In [18]:
A*B

array([[21,  4],
       [36,  3]])

In [19]:
A/B

array([[ 0.42857143,  1.        ],
       [ 0.44444444,  0.33333333]])

In [20]:
B-A

array([[4, 0],
       [5, 2]])

In [21]:
A*A

array([[ 9,  4],
       [16,  1]])

In [22]:
B.sum(axis = 0)  # column wise sum

array([16,  5])

In [23]:
B.sum(axis = 1)  # row wise sum

array([ 9, 12])

In [24]:
A.dot(B)   # matrix multiplication

array([[39, 12],
       [37, 11]])

In [25]:
np.dot(A,B) # other way

array([[39, 12],
       [37, 11]])

In [26]:
B.dot(A)

array([[29, 16],
       [39, 21]])

In [27]:
B.T           # matrix transpose

array([[7, 9],
       [2, 3]])

In [28]:
a = np.random.random((2,3))

In [29]:
a *= 3
a

array([[  1.55953187e+00,   1.03637179e+00,   2.52956362e+00],
       [  2.43427867e-03,   7.75332627e-01,   1.08037014e-01]])

Multidimensional arrays can have one index per axis. These indices are given in a tuple seperated by commas.

In [30]:
def add(x, y):
    return x + y 

In [31]:
a = np.fromfunction(add, (2,2), dtype = int)

In [32]:
print(a)

[[0 1]
 [1 2]]


In [33]:
for row in a:
    print(row * row)

[0 1]
[1 4]


If we want to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array.

In [34]:
for element_in_a in a.flat:
    print(element_in_a)

0
1
1
2


In [35]:
b = np.floor(10* np.random.random((4,2)))
b

array([[ 2.,  9.],
       [ 4.,  6.],
       [ 1.,  4.],
       [ 9.,  7.]])

In [36]:
b.ravel() # returns a flattend array

array([ 2.,  9.,  4.,  6.,  1.,  4.,  9.,  7.])

In [37]:
np.hsplit(b, 2) # splits the array

[array([[ 2.],
        [ 4.],
        [ 1.],
        [ 9.]]), array([[ 9.],
        [ 6.],
        [ 4.],
        [ 7.]])]

In [38]:
c = b # copies 

In [39]:
c

array([[ 2.,  9.],
       [ 4.,  6.],
       [ 1.,  4.],
       [ 9.,  7.]])

In [40]:
c is b

True

In [41]:
np.sqrt(c)

array([[ 1.41421356,  3.        ],
       [ 2.        ,  2.44948974],
       [ 1.        ,  2.        ],
       [ 3.        ,  2.64575131]])

In [42]:
np.log(c)

array([[ 0.69314718,  2.19722458],
       [ 1.38629436,  1.79175947],
       [ 0.        ,  1.38629436],
       [ 2.19722458,  1.94591015]])

In [43]:
np.multiply(b,c)

array([[  4.,  81.],
       [ 16.,  36.],
       [  1.,  16.],
       [ 81.,  49.]])

In [44]:
np.subtract(c,b)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [45]:
print(c.sum()) # array wise sum
print(c.min()) # array wise min value
print(c.max(axis = 1))   # maximum value column wise
print(c.cumsum(axis = 1)) # cummulative sum of the elements
print(c.mean())  # mean
print(c.std())  # standard deviation

42.0
1.0
[ 9.  6.  4.  9.]
[[  2.  11.]
 [  4.  10.]
 [  1.   5.]
 [  9.  16.]]
5.25
2.8173569174


In [46]:
c = np.floor(10*np.random.random((4,3)))
c

array([[ 2.,  8.,  4.],
       [ 3.,  6.,  9.],
       [ 7.,  6.,  3.],
       [ 8.,  8.,  0.]])

In [47]:
print(c[1:4])  # index 1 to 4

[[ 3.  6.  9.]
 [ 7.  6.  3.]
 [ 8.  8.  0.]]


In [48]:
print(c[1:4, 2]) # prints elements of 3rd column from row 2 to 4 (ndex 1 to 4)

[ 9.  3.  0.]


In [49]:
np.info(np.ndarray.dtype)  # for help

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [50]:
np.insert(c, 2,3) # inserts an extra element at 3rd index (2) as 3 

array([ 2.,  8.,  3.,  4.,  3.,  6.,  9.,  7.,  6.,  3.,  8.,  8.,  0.])

In [51]:
np.delete(c, [3]) # removes the 3rd element

array([ 2.,  8.,  4.,  6.,  9.,  7.,  6.,  3.,  8.,  8.,  0.])

# Generating a dummy dataset using Numpy

### Syntax
var = np.round(np.random.normal(distribution mean, standard deviation, number of samples), number of digits after the decimal point)

In [52]:
# Generate height of 10000 people in a city just using numpy 
height = np.round(np.random.normal(1.75, 0.20, 10000),2)

In [53]:
# Generate weight of 10000 people in a city just using numpy
weight = np.round(np.random.normal(60.32, 15, 10000),2)

In [54]:
np_city = np.column_stack((height, weight)) #  column 0 = height, column 1 = weight

In [55]:
np.mean(np_city[:,0]) # mean of height

1.7546360000000001

In [56]:
np.median(np_city[:,1]) # median of weight

59.945

## Creating a label using numpy

In [57]:
np_label = np.random.choice([0,1], size = 10000, p = [0.5,0.5])

In [58]:
np_label[0:10]

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0])